import sys
content = '<!DOCTYPE html>\n'
content += '<html xmlns:th="http://www.thymeleaf.org" xmlns:sec="http://www.thymeleaf.org/extras/spring-security" lang="en">\n'
content += '<head th:replace="~{fragments/header::head(\'Employer Registration - JobPortal\', \'Create your employer account\')}"></head>\n'
content += '<body>\n'
content += '<div class="aurora-bg"></div>\n'
content += '<div class="aurora-blob aurora-blob-1"></div>\n'
content += '<div class="aurora-blob aurora-blob-2"></div>\n'
content += '<div class="mouse-glow"></div>\n'
content += '<div class="auth-container">\n'
content += '<div class="container">\n'
content += '<div class="row justify-content-center">\n'
content += '<div class="col-lg-6">\n'
content += '<div class="glass-card-lg auth-card">\n'
content += '<div class="text-center mb-4">\n'
content += '<a th:href="@{/}" class="d-inline-block mb-3" style="font-size: 2rem;"><i class="fas fa-building" style="color: var(--color-primary);"></i></a>\n'
content += '<h2 class="auth-title">Create Employer Account</h2>\n'
content += '<p class="auth-subtitle">Start hiring top talent for your organization</p>\n'
content += '</div>\n'
content += '<div th:if="${errorMessage}" class="alert alert-danger mb-4">\n'
content += '<i class="fas fa-exclamation-circle alert-icon"></i>\n'
content += '<div class="alert-content" th:text="${errorMessage}">Error</div>\n'
content += '</div>\n'
content += '<div th:if="${emailError}" class="alert alert-danger mb-4">\n'
content += '<i class="fas fa-exclamation-circle alert-icon"></i>\n'
content += '<div class="alert-content" th:text="${emailError}">Email already registered</div>\n'
content += '</div>\n'
content += '<form th:action="@{/employer/register}" th:object="${registerRequest}" method="post" novalidate>\n'
content += '<input type="hidden" name="role" value="ROLE_EMPLOYER" />\n'
content += '<div class="form-group">\n'
content += '<label class="form-label" for="fullName">Full Name</label>\n'
content += '<input type="text" id="fullName" th:field="*{fullName}" class="form-input" placeholder="John Doe" th:classappend="${#fields.hasErrors(\'fullName\')} ? \'is-invalid\' : \'\'" required />\n'
content += '<div th:if="${#fields.hasErrors(\'fullName\')}" class="form-error" th:errors="*{fullName}">Error</div>\n'
content += '</div>\n'
content += '<div class="form-group">\n'
content += '<label class="form-label" for="email">Work Email</label>\n'
content += '<input type="email" id="email" th:field="*{email}" class="form-input" placeholder="you@company.com" th:classappend="${#fields.hasErrors(\'email\')} ? \'is-invalid\' : \'\'" required />\n'
content += '<div th:if="${#fields.hasErrors(\'email\')}" class="form-error" th:errors="*{email}">Error</div>\n'
content += '</div>\n'
content += '<div class="row g-3">\n'
content += '<div class="col-md-6">\n'
content += '<div class="form-group">\n'
content += '<label class="form-label" for="password">Password</label>\n'
content += '<input type="password" id="passwordInput" th:field="*{password}" class="form-input" placeholder="Create a strong password" th:classappend="${#fields.hasErrors(\'password\')} ? \'is-invalid\' : \'\'" required />\n'
content += '<div class="password-strength">\n'
content += '<div class="strength-bar">\n'
content += '<div class="strength-bar-fill" id="strengthBar"></div>\n'
content += '</div>\n'
content += '<div class="strength-text" id="strengthText"></div>\n'
content += '</div>\n'
content += '<div th:if="${#fields.hasErrors(\'password\')}" class="form-error" th:errors="*{password}">Error</div>\n'
content += '</div>\n'
content += '</div>\n'
content += '<div class="col-md-6">\n'
content += '<div class="form-group">\n'
content += '<label class="form-label" for="phone">Phone Number</label>\n'
content += '<input type="tel" id="phone" th:field="*{phone}" class="form-input" placeholder="+1 234 567 890" th:classappend="${#fields.hasErrors(\'phone\')} ? \'is-invalid\' : \'\'" />\n'
content += '<div th:if="${#fields.hasErrors(\'phone\')}" class="form-error" th:errors="*{phone}">Error</div>\n'
content += '</div>\n'
content += '</div>\n'
content += '</div>\n'
content += '<div class="form-group">\n'
content += '<label class="form-check">\n'
content += '<input type="checkbox" required />\n'
content += '<span class="form-check-label">I agree to the <a href="#" style="color: var(--color-primary);">Terms of Service</a> and <a href="#" style="color: var(--color-primary);">Privacy Policy</a></span>\n'
content += '</label>\n'
content += '</div>\n'
content += '<button type="submit" class="btn btn-primary-gradient btn-lg w-100"><i class="fas fa-building"></i> Create Employer Account</button>\n'
content += '</form>\n'
content += '<div class="text-center mt-4">\n'
content += '<p style="color: var(--text-secondary); font-size: var(--font-size-sm);">Already have an account? <a th:href="@{/login}" style="color: var(--color-primary); font-weight: var(--font-weight-semibold);">Sign in</a></p>\n'
content += '<a th:href="@{/register}" class="btn btn-ghost btn-sm mt-2"><i class="fas fa-arrow-left me-1"></i> Choose different role</a>\n'
content += '</div>\n'
content += '</div>\n'
content += '</div>\n'
content += '</div>\n'
content += '</div>\n'
content += '</div>\n'
content += '<div th:replace="~{fragments/header::scripts}"></div>\n'
content += '</body>\n'
content += '</html>\n'

with open('src/main/resources/templates/auth/employer-register.html', 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Written {len(content)} bytes to employer-register.html')
