import re

# Build the complete dashboard HTML
lines = []

# Header
lines.append('<!DOCTYPE html>')
lines.append('<html xmlns:th="http://www.thymeleaf.org"')
lines.append('      xmlns:sec="http://www.thymeleaf.org/extras/spring-security"')
lines.append('      lang="en">')
lines.append('<head th:replace="~{fragments/header::head(\'Employer Dashboard - JobPortal\', \'Your recruitment dashboard\')}"></head>')
lines.append('<body>')
lines.append('<div th:replace="~{fragments/employer-sidebar::sidebar(\'Dashboard\', \'dashboard\')}"></div>')
lines.append('<div class="dashboard-main">')
lines.append('    <div class="container-fluid">')

# Welcome Section
lines.append('        <div class="glass-card-lg p-5 mb-5 fade-in">')
lines.append('            <div class="row align-items-center">')
lines.append('                <div class="col-lg-8">')
lines.append('                    <div class="d-flex align-items-center gap-4 mb-3">')
lines.append('                        <div class="profile-avatar" style="width: 72px; height: 72px; font-size: 2rem;">')
lines.append('                            <span th:text="${currentUser != null ? #strings.substring(currentUser.fullName, 0, 1) : \'E\'}">E</span>')
lines.append('                        </div>')
lines.append('                        <div>')
lines.append('                            <h2 class="fw-bold mb-1" style="font-size: 1.8rem;">Welcome back, <span th:text="${currentUser?.fullName ?: \'Employer\'}">Employer</span></h2>')
lines.append('                            <p style="color: var(--text-secondary);">Your recruitment hub. Manage jobs, review applicants, and find top talent.</p>')
lines.append('                        </div>')
lines.append('                    </div>')
lines.append('                    <div class="d-flex flex-wrap gap-3 mt-4">')
lines.append('                        <a th:href="@{/employer/jobs/post}" class="btn btn-primary-gradient"><i class="fas fa-plus"></i> Post New Job</a>')
lines.append('                        <a th:href="@{/employer/applicants}" class="btn btn-secondary-glass"><i class="fas fa-users"></i> View Applicants</a>')
lines.append('                    </div>')
lines.append('                </div>')
lines.append('                <div class="col-lg-4 d-none d-lg-block">')
lines.append('                    <div class="glass p-4 text-center">')
lines.append('                        <div style="font-size: 0.8rem; color: var(--text-muted); margin-bottom: 0.5rem;">Jobs Posted</div>')
lines.append('                        <div style="font-size: 2.5rem; font-weight: 800; color: var(--color-primary);" th:text="${stats?.employerJobCount ?: 0}">0</div>')
lines.append('                    </div>')
lines.append('                </div>')
lines.append('            </div>')
lines.append('        </div>')

# Statistics Cards
lines.append('        <div class="row g-4 mb-5">')
lines.append('            <div class="col-6 col-xl-2">')
lines.append('                <div class="stats-card card fade-in">')
lines.append('                    <div class="stats-icon primary"><i class="fas fa-briefcase"></i></div>')
lines.append('                    <div class="stats-number count-up" th:attr="data-target=${stats != null ? stats.employerJobCount : 0}" th:text="${stats?.employerJobCount ?: 0}">0</div>')
lines.append('                    <div class="stats-label">Jobs Posted</div>')
lines.append('                </div>')
lines.append('            </div>')
lines.append('            <div class="col-6 col-xl-2">')
lines.append('                <div class="stats-card card fade-in">')
lines.append('                    <div class="stats-icon success"><i class="fas fa-check-circle"></i></div>')
lines.append('                    <div class="stats-number count-up" th:attr="data-target=${stats != null ? stats.employerActiveJobs : 0}" th:text="${stats?.employerActiveJobs ?: 0}">0</div>')
lines.append('                    <div class="stats-label">Active Jobs</div>')
lines.append('                </div>')
lines.append('            </div>')
lines.append('            <div class="col-6 col-xl-2">')
lines.append('                <div class="stats-card card fade-in">')
lines.append('                    <div class="stats-icon info"><i class="fas fa-users"></i></div>')
lines.append('                    <div class="stats-number count-up" th:attr="data-target=${stats != null ? stats.employerTotalApplications : 0}" th:text="${stats?.employerTotalApplications ?: 0}">0</div>')
lines.append('                    <div class="stats-label">Total Applicants</div>')
lines.append('                </div>')
lines.append('            </div>')
lines.append('            <div class="col-6 col-xl-2">')
lines.append('                <div class="stats-card card fade-in">')
lines.append('                    <div class="stats-icon warning"><i class="fas fa-clock"></i></div>')
lines.append('                    <div class="stats-number count-up" th:attr="data-target=${stats != null ? stats.employerPendingApplications : 0}" th:text="${stats?.employerPendingApplications ?: 0}">0</div>')
lines.append('                    <div class="stats-label">Pending</div>')
lines.append('                </div>')
lines.append('            </div>')
lines.append('            <div class="col-6 col-xl-2">')
lines.append('                <div class="stats-card card fade-in">')
lines.append('                    <div class="stats-icon pink"><i class="fas fa-search"></i></div>')
lines.append('                    <div class="stats-number count-up" th:attr="data-target=${stats != null ? stats.employerReviewedApplications : 0}" th:text="${stats?.employerReviewedApplications ?: 0}">0</div>')
lines.append('                    <div class="stats-label">Reviewing</div>')
lines.append('                </div>')
lines.append('            </div>')
lines.append('            <div class="col-6 col-xl-2">')
lines.append('                <div class="stats-card card fade-in">')
lines.append('                    <div class="stats-icon pink"><i class="fas fa-calendar-check"></i></div>')
lines.append('                    <div class="stats-number count-up" th:attr="data-target=${stats != null ? stats.employerTotalApplications : 0}" th:text="${stats?.employerTotalApplications ?: 0}">0</div>')
lines.append('                    <div class="stats-label">Interviews</div>')
lines.append('                </div>')
lines.append('            </div>')
lines.append('        </div>')

# Main Content
lines.append('        <div class="row g-4">')
lines.append('            <div class="col-lg-8">')
lines.append('                <div class="card mb-4">')
lines.append('                    <div class="card-header">')
lines.append('                        <h5 class="fw-bold mb-0"><i class="fas fa-chart-line me-2" style="color: var(--color-primary);"></i> Applications Over Time</h5>')
lines.append('                    </div>')
lines.append('                    <div class="card-body">')
lines.append('                        <canvas id="applicationsChart" height="220"></canvas>')
lines.append('                    </div>')
lines.append('                </div>')
lines.append('                <div class="card mb-4">')
lines.append('                    <div class="card-header d-flex justify-content-between align-items-center">')
lines.append('                        <h5 class="fw-bold mb-0"><i class="fas fa-briefcase me-2" style="color: var(--color-info);"></i> Your Recent Jobs</h5>')
lines.append('                        <a th:href="@{/employer/jobs}" class="btn btn-ghost btn-sm">View All <i class="fas fa-arrow-right ms-1"></i></a>')
lines.append('                    </div>')
lines.append('                    <div class="card-body p-0">')
lines.append('                        <div th:if="${recentJobs != null and !recentJobs.isEmpty()}">')
lines.append('                            <div th:each="job : ${recentJobs}" class="px-4 py-3" style="border-bottom: 1px solid var(--border-secondary);">')
lines.append('                                <div class="d-flex justify-content-between align-items-center">')
lines.append('                                    <div>')
lines.append('                                        <div class="fw-semibold" th:text="${job.title()}">Job Title</div>')
lines.append('                                        <div style="font-size: var(--font-size-xs); color: var(--text-muted);">')
lines.append('                                            <span th:text="${job.applicationCount()}">0</span> applicants')
lines.append('                                            <span class="ms-2" th:if="${job.active()}">Active</span>')
lines.append('                                            <span class="ms-2" th:unless="${job.active()}">Inactive</span>')
lines.append('                                        </div>')
lines.append('                                    </div>')
lines.append('                                    <span class="badge bg-primary" th:text="${#temporals.format(job.createdAt(), \'MMM dd\')}">Date</span>')
lines.append('                                </div>')
lines.append('                            </div>')
lines.append('                        </div>')
lines.append('                        <div th:if="${recentJobs == null or recentJobs.isEmpty()}" class="empty-state p-4 text-center">')
lines.append('                            <div class="empty-icon" style="font-size: 2rem;"><i class="fas fa-briefcase"></i></div>')
lines.append('                            <h4>No jobs posted yet</h4>')
lines.append('                            <p>Post your first job to start receiving applications.</p>')
lines.append('                            <a th:href="@{/employer/jobs/post}" class="btn btn-primary-gradient">Post a Job</a>')
lines.append('                        </div>')
lines.append('                    </div>')
lines.append('                </div>')
lines.append('                <div class="card mb-4">')
lines.append('                    <div class="card-header">')
lines.append('                        <h5 class="fw-bold mb-0"><i class="fas fa-filter me-2" style="color: var(--color-primary);"></i> Hiring Pipeline</h5>')
lines.append('                    </div>')
lines.append('                    <div class="card-body">')
lines.append('                        <div class="row g-3 text-center">')
lines.append('                            <div class="col-3">')
lines.append('                                <div class="glass p-3">')
lines.append('                                    <div class="fw-bold" style="font-size: 1.5rem; color: var(--color-warning);" th:text="${stats?.employerPendingApplications ?: 0}">0</div>')
lines.append('                                    <div style="font-size: var(--font-size-xs); color: var(--text-muted);">Applied</div>')
lines.append('                                </div>')
lines.append('                            </div>')
lines.append('                            <div class="col-3">')
lines.append('                                <div class="glass p-3">')
lines.append('                                    <div class="fw-bold" style="font-size: 1.5rem; color: var(--color-info);" th:text="${stats?.employerReviewedApplications ?: 0}">0</div>')
lines.append('                                    <div style="font-size: var(--font-size-xs); color: var(--text-muted);">Reviewing</div>')
lines.append('                                </div>')
lines.append('                            </div>')
lines.append('                            <div class="col-3">')
lines.append('                                <div class="glass p-3">')
lines.append('                                    <div class="fw-bold" style="font-size: 1.5rem; color: var(--color-primary);">0</div>')
lines.append('                                    <div style="font-size: var(--font-size-xs); color: var(--text-muted);">Shortlisted</div>')
lines.append('                                </div>')
lines.append('                            </div>')
lines.append('                            <div class="col-3">')
lines.append('                                <div class="glass p-3">')
lines.append('                                    <div class="fw-bold" style="font-size: 1.5rem; color: var(--color-success);">0</div>')
lines.append('                                    <div style="font-size: var(--font-size-xs); color: var(--text-muted);">Hired</div>')
lines.append('                                </div>')
lines.append('                            </div>')
lines.append('                        </div>')
lines.append('                    </div>')
lines.append('                </div>')
lines.append('            </div>')
lines.append('            <div class="col-lg-4">')
lines.append('                <div class="card mb-4">')
lines.append('                    <div class="card-header">')
lines.append('                        <h5 class="fw-bold mb-0"><i class="fas fa-trophy me-2" style="color: var(--color-warning);"></i> Top Jobs</h5>')
lines.append('                    </div>')
lines.append('                    <div class="card-body p-0">')
lines.append('                        <div th:if="${recentJobs != null and !recentJobs.isEmpty()}">')
lines.append('                            <div th:each="job, iterStat : ${recentJobs}" th:if="${iterStat.index < 5}" class="px-4 py-3" style="border-bottom: 1px solid var(--border-secondary);">')
lines.append('                                <div class="fw-semibold" style="font-size: var(--font-size-sm);" th:text="${job.title()}">Job</div>')
lines.append('                                <div style="font-size: var(--font-size-xs); color: var(--text-muted);">')
lines.append('                                    <span th:text="${job.applicationCount()}">0</span> applicants')
lines.append('                                </div>')
lines.append('                            </div>')
lines.append('                        </div>')
lines.append('                        <div th:if="${recentJobs == null or recentJobs.isEmpty()}" class="empty-state p-4 text-center">')
lines.append('                            <p>Post your first job to see performance here.</p>')
lines.append('                        </div>')
lines.append('                    </div>')
lines.append('                </div>')
lines.append('                <div class="card mb-4">')
lines.append('                    <div class="card-header">')
lines.append('                        <h5 class="fw-bold mb-0"><i class="fas fa-chart-pie me-2" style="color: var(--color-primary);"></i> Applications by Job</h5>')
lines.append('                    </div>')
lines.append('                    <div class="card-body">')
lines.append('                        <canvas id="jobsPieChart" height="250"></canvas>')
lines.append('                    </div>')
lines.append('                </div>')
lines.append('                <div class="card mb-4">')
lines.append('                    <div class="card-header">')
lines.append('                        <h5 class="fw-bold mb-0"><i class="fas fa-bolt me-2" style="color: var(--color-warning);"></i> Activity Feed</h5>')
lines.append('                    </div>')
lines.append('                    <div class="card-body p-0">')
lines.append('                        <div th:if="${recentJobs != null and !recentJobs.isEmpty()}">')
lines.append('                            <div th:each="job : ${recentJobs}" class="activity-item px-4">')
lines.append('                                <div class="activity-icon badge bg-primary"><i class="fas fa-briefcase"></i></div>')
lines.append('                                <div class="activity-content">')
lines.append('                                    <div class="activity-text">')
lines.append('                                        Job posted: <strong th:text="${job.title()}">Title</strong>')
lines.append('                                    </div>')
lines.append('                                    <div class="activity-time" th:text="${#temporals.format(job.createdAt(), \'MMM dd, yyyy\')}">Date</div>')
lines.append('                                </div>')
lines.append('                            </div>')
lines.append('                        </div>')
lines.append('                        <div th:if="${recentJobs == null or recentJobs.isEmpty()}" class="empty-state p-4 text-center">')
lines.append('                            <p>No recent activity.</p>')
lines.append('                        </div>')
lines.append('                    </div>')
lines.append('                </div>')
lines.append('            </div>')
lines.append('        </div>')
lines.append('    </div>')
lines.append('</div>')

# Charts JavaScript
lines.append('<script>')
lines.append("document.addEventListener('DOMContentLoaded', function() {")
lines.append("    var ctx = document.getElementById('applicationsChart');")
lines.append('    if (ctx) {')
lines.append("        ctx = ctx.getContext('2d');")
lines.append('        new Chart(ctx, {')
lines.append("            type: 'line',")
lines.append('            data: {')
lines.append("                labels: ['Week 1', 'Week 2', 'Week 3', 'Week 4'],")
lines.append('                datasets: [{')
lines.append("                    label: 'Applications',")
lines.append('                    data: [0, 0, 0, 0],')
lines.append("                    borderColor: '#6366f1',")
lines.append("                    backgroundColor: 'rgba(99, 102, 241, 0.1)',")
lines.append('                    tension: 0.4,')
lines.append('                    fill: true')
lines.append('                }]')
lines.append('            },')
lines.append('            options: {')
lines.append('                responsive: true,')
lines.append('                maintainAspectRatio: false,')
lines.append('                plugins: { legend: { display: false } },')
lines.append('                scales: {')
lines.append("                    y: { beginAtZero: true, grid: { color: 'rgba(255,255,255,0.05)' } },")
lines.append('                    x: { grid: { display: false } }')
lines.append('                }')
lines.append('            }')
lines.append('        });')
lines.append('    }')
lines.append("    var ctx2 = document.getElementById('jobsPieChart');")
lines.append('    if (ctx2) {')
lines.append("        ctx2 = ctx2.getContext('2d');")
lines.append('        new Chart(ctx2, {')
lines.append("            type: 'doughnut',")
lines.append('            data: {')
lines.append("                labels: ['Applications'],")
lines.append('                datasets: [{')
lines.append('                    data: [1],')
lines.append("                    backgroundColor: ['#6366f1', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6']")
lines.append('                }]')
lines.append('            },')
lines.append('            options: {')
lines.append('                responsive: true,')
lines.append('                maintainAspectRatio: false,')
lines.append('                plugins: { legend: { position: \'bottom\' } }')
lines.append('            }')
lines.append('        });')
lines.append('    }')
lines.append('});')
lines.append('</script>')

lines.append('<div th:replace="~{fragments/header::scripts}"></div>')
lines.append('</body>')
lines.append('</html>')

html = '\n'.join(lines)

with open('src/main/resources/templates/employer/dashboard.html', 'w', encoding='utf-8') as f:
    f.write(html)

# Verify
with open('src/main/resources/templates/employer/dashboard.html', encoding='utf-8') as f:
    c = f.read()

print(f'File size: {len(c)} bytes')
opens = len(re.findall(r'<div(?:\s|>)', c))
closes = c.count('</div>')
print(f'divs: {opens} open, {closes} close (diff={opens-closes})')
span_o = len(re.findall(r'<span(?:\s|>)', c))
span_c = c.count('</span>')
print(f'spans: {span_o} open, {span_c} close (diff={span_o-span_c})')

# Tag stack validation
tags = re.findall(r'<(/?)(\w+)', c)
void = {'br','hr','img','input','meta','link','DOCTYPE','canvas','!DOCTYPE'}
stack = []
for is_close, tag in tags:
    if tag in void:
        continue
    if not is_close:
        stack.append(tag)
    elif stack and stack[-1] == tag:
        stack.pop()
    else:
        stack.append(f'UNMATCHED_CLOSE_{tag}')

print(f'Tag stack remaining: {len(stack)} - {"PASS" if len(stack) == 0 else "FAIL"}')
if stack:
    print(f'  Issues: {stack[:10]}')
