import sys
content = '<!DOCTYPE html>\n'
content += '<html xmlns:th="http://www.thymeleaf.org"\n'
content += '      xmlns:sec="http://www.thymeleaf.org/extras/spring-security"\n'
content += '      lang="en">\n'
content += '<head th:replace="~{fragments/header::head(\'About Us - JobPortal\', \'Learn about JobPortal\')}"></head>\n'
content += '<body>\n'
content += '    <div class="aurora-bg"></div>\n'
content += '    <div class="aurora-blob aurora-blob-1"></div>\n'
content += '    <div class="aurora-blob aurora-blob-2"></div>\n'
content += '    <div class="aurora-blob aurora-blob-3"></div>\n'
content += '    <div class="mouse-glow"></div>\n'
content += '    <nav th:replace="~{fragments/header::navbar}"></nav>\n'
content += '    <!-- Hero Section -->\n'
content += '    <section class="position-relative pt-5" style="margin-top: 76px;">\n'
content += '        <div class="container text-center py-5">\n'
content += '            <div class="glass-card-lg p-5 fade-in">\n'
content += '                <span class="badge badge-primary mb-3"><i class="fas fa-info-circle me-1"></i> About Us</span>\n'
content += '                <h1 class="display-4 fw-bold mb-3 gradient-text">About JobPortal</h1>\n'
content += '                <p class="lead mb-0" style="color: var(--text-secondary); max-width: 600px; margin: 0 auto;">Connecting talented professionals with amazing career opportunities worldwide</p>\n'
content += '            </div>\n'
content += '        </div>\n'
content += '    </section>\n'
content += '    <!-- Mission & Vision -->\n'
content += '    <section class="py-5">\n'
content += '        <div class="container">\n'
content += '            <div class="row g-4">\n'
content += '                <div class="col-md-6">\n'
content += '                    <div class="card h-100 p-4 fade-in">\n'
content += '                        <div class="d-flex align-items-center mb-3">\n'
content += '                            <div class="stats-icon primary me-3"><i class="fas fa-bullseye"></i></div>\n'
content += '                            <h3 class="fw-bold mb-0">Our Mission</h3>\n'
content += '                        </div>\n'
content += '                        <p style="color: var(--text-secondary); line-height: 1.8;">To revolutionize the job search experience by providing a seamless, intelligent platform that connects job seekers with their dream careers and employers with top talent.</p>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '                <div class="col-md-6">\n'
content += '                    <div class="card h-100 p-4 fade-in">\n'
content += '                        <div class="d-flex align-items-center mb-3">\n'
content += '                            <div class="stats-icon info me-3"><i class="fas fa-eye"></i></div>\n'
content += '                            <h3 class="fw-bold mb-0">Our Vision</h3>\n'
content += '                        </div>\n'
content += '                        <p style="color: var(--text-secondary); line-height: 1.8;">To become the world\'s most trusted and innovative job portal, empowering millions of professionals to build successful careers and organizations to build exceptional teams.</p>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '            </div>\n'
content += '        </div>\n'
content += '    </section>\n'
content += '    <!-- Features -->\n'
content += '    <section class="py-5">\n'
content += '        <div class="container">\n'
content += '            <div class="text-center mb-5 fade-in">\n'
content += '                <span class="badge badge-primary mb-2"><i class="fas fa-gem me-1"></i> Why Choose Us</span>\n'
content += '                <h2 class="section-title">Why Choose JobPortal?</h2>\n'
content += '                <p class="section-subtitle">Built for career success with cutting-edge technology</p>\n'
content += '            </div>\n'
content += '            <div class="row g-4">\n'
content += '                <div class="col-md-4">\n'
content += '                    <div class="card p-4 text-center h-100 fade-in">\n'
content += '                        <div class="stats-icon primary mx-auto mb-3"><i class="fas fa-search"></i></div>\n'
content += '                        <h5 class="fw-bold mb-2">Smart Job Search</h5>\n'
content += '                        <p style="color: var(--text-secondary); font-size: 0.9rem; line-height: 1.7;">Advanced filtering and search algorithms to find the perfect job match quickly.</p>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '                <div class="col-md-4">\n'
content += '                    <div class="card p-4 text-center h-100 fade-in">\n'
content += '                        <div class="stats-icon info mx-auto mb-3"><i class="fas fa-shield-alt"></i></div>\n'
content += '                        <h5 class="fw-bold mb-2">Verified Employers</h5>\n'
content += '                        <p style="color: var(--text-secondary); font-size: 0.9rem; line-height: 1.7;">All employers are verified to ensure legitimate and quality job opportunities.</p>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '                <div class="col-md-4">\n'
content += '                    <div class="card p-4 text-center h-100 fade-in">\n'
content += '                        <div class="stats-icon success mx-auto mb-3"><i class="fas fa-rocket"></i></div>\n'
content += '                        <h5 class="fw-bold mb-2">Easy Application</h5>\n'
content += '                        <p style="color: var(--text-secondary); font-size: 0.9rem; line-height: 1.7;">One-click apply with resume upload for a frictionless application process.</p>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '            </div>\n'
content += '        </div>\n'
content += '    </section>\n'
content += '    <!-- Stats -->\n'
content += '    <section class="py-5">\n'
content += '        <div class="container">\n'
content += '            <div class="row g-4 text-center">\n'
content += '                <div class="col-md-3 col-6">\n'
content += '                    <div class="stats-card card fade-in">\n'
content += '                        <div class="stats-icon primary mx-auto mb-3"><i class="fas fa-briefcase"></i></div>\n'
content += '                        <div class="stats-number count-up" data-target="10000">0</div>\n'
content += '                        <div class="stats-label">Active Jobs</div>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '                <div class="col-md-3 col-6">\n'
content += '                    <div class="stats-card card fade-in">\n'
content += '                        <div class="stats-icon success mx-auto mb-3"><i class="fas fa-users"></i></div>\n'
content += '                        <div class="stats-number count-up" data-target="50000">0</div>\n'
content += '                        <div class="stats-label">Job Seekers</div>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '                <div class="col-md-3 col-6">\n'
content += '                    <div class="stats-card card fade-in">\n'
content += '                        <div class="stats-icon warning mx-auto mb-3"><i class="fas fa-building"></i></div>\n'
content += '                        <div class="stats-number count-up" data-target="5000">0</div>\n'
content += '                        <div class="stats-label">Companies</div>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '                <div class="col-md-3 col-6">\n'
content += '                    <div class="stats-card card fade-in">\n'
content += '                        <div class="stats-icon info mx-auto mb-3"><i class="fas fa-smile"></i></div>\n'
content += '                        <div class="stats-number count-up" data-target="95">0</div>\n'
content += '                        <div class="stats-label">Satisfaction %</div>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '            </div>\n'
content += '        </div>\n'
content += '    </section>\n'
content += '    <!-- Team -->\n'
content += '    <section class="py-5">\n'
content += '        <div class="container">\n'
content += '            <div class="text-center mb-5 fade-in">\n'
content += '                <span class="badge badge-success mb-2"><i class="fas fa-users me-1"></i> Our Team</span>\n'
content += '                <h2 class="section-title">Meet Our Team</h2>\n'
content += '                <p class="section-subtitle">Dedicated professionals driving innovation in career development</p>\n'
content += '            </div>\n'
content += '            <div class="row g-4 justify-content-center">\n'
content += '                <div class="col-md-4">\n'
content += '                    <div class="card p-4 text-center fade-in">\n'
content += '                        <img src="https://ui-avatars.com/api/?name=John+Doe&size=128&background=8b5cf6&color=fff&rounded=true&bold=true" alt="John Doe" class="rounded-circle mx-auto mb-3" width="100" height="100">\n'
content += '                        <h5 class="fw-bold mb-1">John Doe</h5>\n'
content += '                        <p style="color: var(--text-muted); font-size: var(--font-size-sm);">CEO &amp; Founder</p>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '                <div class="col-md-4">\n'
content += '                    <div class="card p-4 text-center fade-in">\n'
content += '                        <img src="https://ui-avatars.com/api/?name=Jane+Smith&size=128&background=3b82f6&color=fff&rounded=true&bold=true" alt="Jane Smith" class="rounded-circle mx-auto mb-3" width="100" height="100">\n'
content += '                        <h5 class="fw-bold mb-1">Jane Smith</h5>\n'
content += '                        <p style="color: var(--text-muted); font-size: var(--font-size-sm);">Chief Technology Officer</p>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '                <div class="col-md-4">\n'
content += '                    <div class="card p-4 text-center fade-in">\n'
content += '                        <img src="https://ui-avatars.com/api/?name=Mike+Johnson&size=128&background=10b981&color=fff&rounded=true&bold=true" alt="Mike Johnson" class="rounded-circle mx-auto mb-3" width="100" height="100">\n'
content += '                        <h5 class="fw-bold mb-1">Mike Johnson</h5>\n'
content += '                        <p style="color: var(--text-muted); font-size: var(--font-size-sm);">Head of Operations</p>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '            </div>\n'
content += '        </div>\n'
content += '    </section>\n'
content += '    <footer th:replace="~{fragments/footer::footer}"></footer>\n'
content += '    <div th:replace="~{fragments/header::scripts}"></div>\n'
content += '</body>\n'
content += '</html>\n'
with open('src/main/resources/templates/about.html', 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Written {len(content)} bytes to about.html')
