content = '<!DOCTYPE html>\n'
content += '<html xmlns:th="http://www.thymeleaf.org"\n'
content += '      xmlns:sec="http://www.thymeleaf.org/extras/spring-security"\n'
content += '      lang="en">\n'
content += '<head th:replace="~{fragments/header::head(\'Browse Jobs - JobPortal\', \'Find your dream job\')}"></head>\n'
content += '<body>\n'
content += '    <div class="aurora-bg"></div>\n'
content += '    <div class="aurora-blob aurora-blob-1"></div>\n'
content += '    <div class="aurora-blob aurora-blob-2"></div>\n'
content += '    <div class="mouse-glow"></div>\n'
content += '    <nav th:replace="~{fragments/header::navbar}"></nav>\n'
content += '    <section class="pt-5 pb-4">\n'
content += '        <div class="container">\n'
content += '            <div class="glass-card-lg p-5 fade-in">\n'
content += '                <div class="text-center mb-4">\n'
content += '                    <h1 class="fw-bold mb-2 gradient-text" style="font-size: 2.5rem; letter-spacing: -1px;">Find Your Dream Job</h1>\n'
content += '                    <p style="color: var(--text-secondary); font-size: var(--font-size-lg);">Browse thousands of opportunities from top companies</p>\n'
content += '                </div>\n'
content += '                <form th:action="@{/jobs/search}" method="get" class="row g-3 align-items-end">\n'
content += '                    <div class="col-md-5">\n'
content += '                        <div class="form-group mb-0 position-relative">\n'
content += '                            <i class="fas fa-search" style="position: absolute; left: 16px; top: 50%; transform: translateY(-50%); color: var(--text-muted); z-index: 2;"></i>\n'
content += '                            <input type="text" name="keyword" class="form-input" style="padding-left: 44px;" placeholder="Job title, skill, or keyword..." th:value="${keyword}">\n'
content += '                        </div>\n'
content += '                    </div>\n'
content += '                    <div class="col-md-3">\n'
content += '                        <div class="form-group mb-0 position-relative">\n'
content += '                            <i class="fas fa-map-marker-alt" style="position: absolute; left: 16px; top: 50%; transform: translateY(-50%); color: var(--text-muted); z-index: 2;"></i>\n'
content += '                            <input type="text" name="location" class="form-input" style="padding-left: 44px;" placeholder="City or remote..." th:value="${location}">\n'
content += '                        </div>\n'
content += '                    </div>\n'
content += '                    <div class="col-md-2">\n'
content += '                        <select name="employmentType" class="form-input" style="min-height: 48px;">\n'
content += '                            <option value="">All Types</option>\n'
content += '                            <option th:each="type : ${employmentTypes}" th:value="${type}" th:text="${type}" th:selected="${#strings.equals(employmentType, type)}">Type</option>\n'
content += '                        </select>\n'
content += '                    </div>\n'
content += '                    <div class="col-md-2">\n'
content += '                        <button type="submit" class="btn btn-primary-gradient w-100" style="min-height: 48px;">\n'
content += '                            <i class="fas fa-search"></i> Search\n'
content += '                        </button>\n'
content += '                    </div>\n'
content += '                </form>\n'
content += '            </div>\n'
content += '        </div>\n'
content += '    </section>\n'
content += '    <section class="pb-5">\n'
content += '        <div class="container">\n'
content += '            <div class="row g-4">\n'
content += '                <div class="col-lg-3">\n'
content += '                    <div class="card sticky-top" style="top: 100px;">\n'
content += '                        <div class="card-header d-flex justify-content-between align-items-center">\n'
content += '                            <h5 class="fw-bold mb-0"><i class="fas fa-filter me-2" style="color: var(--color-primary);"></i> Filters</h5>\n'
content += '                            <a th:href="@{/jobs}" class="btn btn-ghost btn-sm">Clear</a>\n'
content += '                        </div>\n'
content += '                        <div class="card-body">\n'
content += '                            <form th:action="@{/jobs}" method="get">\n'
content += '                                <div class="mb-3">\n'
content += '                                    <label class="form-label">Experience Level</label>\n'
content += '                                    <select name="experienceLevel" class="form-input">\n'
content += '                                        <option value="">Any</option>\n'
content += '                                        <option th:each="level : ${experienceLevels}" th:value="${level}" th:text="${level}" th:selected="${#strings.equals(param.experienceLevel, level)}">Level</option>\n'
content += '                                    </select>\n'
content += '                                </div>\n'
content += '                                <div class="mb-3">\n'
content += '                                    <label class="form-label">Salary Min</label>\n'
content += '                                    <select name="salaryMin" class="form-input">\n'
content += '                                        <option value="">Any</option>\n'
content += '                                        <option value="30000">$30k+</option>\n'
content += '                                        <option value="50000">$50k+</option>\n'
content += '                                        <option value="80000">$80k+</option>\n'
content += '                                        <option value="100000">$100k+</option>\n'
content += '                                        <option value="150000">$150k+</option>\n'
content += '                                    </select>\n'
content += '                                </div>\n'
content += '                                <button type="submit" class="btn btn-primary-gradient w-100"><i class="fas fa-filter"></i> Apply Filters</button>\n'
content += '                            </form>\n'
content += '                        </div>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '                <div class="col-lg-9">\n'
content += '                    <div class="d-flex justify-content-between align-items-center mb-4">\n'
content += '                        <h4 class="fw-bold mb-0"><span th:text="${totalJobs ?: 0}">0</span> Jobs Found</h4>\n'
content += '                    </div>\n'
content += '                    <div id="jobResults">\n'
content += '                        <div th:if="${jobs != null and !jobs.isEmpty()}">\n'
content += '                            <div class="row g-3" id="jobGrid">\n'
content += '                                <div th:each="job : ${jobs}" class="col-md-6 col-xl-4">\n'
content += '                                    <div class="glass-card job-card card-lift h-100 p-4">\n'
content += '                                        <div class="d-flex align-items-start gap-3 mb-3">\n'
content += '                                            <div class="job-company-logo"><i class="fas fa-building"></i></div>\n'
content += '                                            <div class="flex-grow-1" style="min-width: 0;">\n'
content += '                                                <a th:href="@{\'/jobs/view/\' + ${job.id()}}" class="text-decoration-none"><h5 class="job-title" th:text="${job.title()}">Job Title</h5></a>\n'
content += '                                                <div class="job-company"><i class="fas fa-building me-1"></i><span th:text="${job.company()}">Company</span></div>\n'
content += '                                            </div>\n'
content += '                                        </div>\n'
content += '                                        <div class="job-tags">\n'
content += '                                            <span class="badge badge-primary"><i class="fas fa-map-marker-alt me-1"></i> <span th:text="${job.location()}">Location</span>\n'
content += '                                            <span class="badge badge-success" th:if="${job.salaryRange() != null}"><i class="fas fa-dollar-sign me-1"></i> <span th:text="${job.salaryRange()}">Salary</span>\n'
content += '                                            <span class="badge badge-info" th:if="${job.employmentType() != null}" th:text="${job.employmentType()}">Type</span>\n'
content += '                                        </div>\n'
content += '                                        <p style="color: var(--text-secondary); font-size: var(--font-size-sm); display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; margin: 0.75rem 0;"\n'
content += '                                           th:text="${#strings.abbreviate(job.description(), 120)}">Description</p>\n'
content += '                                        <div class="job-meta mt-auto">\n'
content += '                                            <span class="job-date"><i class="far fa-clock me-1"></i> <span th:text="${#temporals.format(job.createdAt(), \'MMM dd, yyyy\')}">Date</span>\n'
content += '                                            <a th:href="@{\'/jobs/view/\' + ${job.id()}}" class="btn btn-secondary-glass btn-sm"><i class="fas fa-eye"></i> Details</a>\n'
content += '                                        </div>\n'
content += '                                    </div>\n'
content += '                                </div>\n'
content += '                            </div>\n'
content += '                        </div>\n'
content += '                        <div th:if="${jobs == null or jobs.isEmpty()}" class="empty-state" style="min-height: 300px;">\n'
content += '                            <div class="empty-icon"><i class="fas fa-search"></i></div>\n'
content += '                            <h4>No jobs found</h4>\n'
content += '                            <p>Try adjusting your search filters or browse by category.</p>\n'
content += '                            <a th:href="@{/jobs}" class="btn btn-primary-gradient">Clear Filters</a>\n'
content += '                        </div>\n'
content += '                    </div>\n'
content += '                    <div th:if="${totalPages > 1}" class="d-flex justify-content-center mt-4">\n'
content += '                        <nav><ul class="pagination">\n'
content += '                            <li th:each="i : ${#numbers.sequence(0, totalPages - 1)}" class="page-item" th:classappend="${i == currentPage} ? \'active\' : \'\'">\n'
content += '                                <a class="page-link" th:href="@{/jobs(page=${i})}" th:text="${i + 1}">1</a>\n'
content += '                            </li>\n'
content += '                        </ul></nav>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '            </div>\n'
content += '        </div>\n'
content += '    </section>\n'
content += '    <footer th:replace="~{fragments/footer::footer}"></footer>\n'
content += '    <div th:replace="~{fragments/header::scripts}"></div>\n'
content += '</body>\n'
content += '</html>\n'
with open('src/main/resources/templates/jobs/browse.html', 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Written {len(content)} bytes to browse.html')
