def write_file(path, content):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Written {len(content)} bytes to {path}')

# ===== FIX: student/profile.html =====
content = '<!DOCTYPE html>\n'
content += '<html xmlns:th="http://www.thymeleaf.org"\n      xmlns:sec="http://www.thymeleaf.org/extras/spring-security"\n      lang="en">\n'
content += '<head th:replace="~{fragments/header::head(\'My Profile - JobPortal\', \'Manage your profile\')}"></head>\n'
content += '<body>\n'
content += '    <div class="aurora-bg"></div>\n'
content += '    <div class="aurora-blob aurora-blob-1"></div>\n'
content += '    <div class="aurora-blob aurora-blob-2"></div>\n'
content += '    <div class="mouse-glow"></div>\n'
content += '    <nav th:replace="~{fragments/header::navbar}"></nav>\n'
content += '    <div class="container py-5" style="max-width: 1200px; margin-top: 76px;">\n'
content += '        <div class="row g-4">\n'
content += '            <div class="col-lg-3">\n'
content += '                <div th:replace="~{fragments/student-sidebar::sidebar(\'Profile\', \'profile\')}"></div>\n'
content += '            </div>\n'
content += '            <div class="col-lg-9">\n'
content += '                <div class="glass-card-lg p-4 fade-in">\n'
content += '                    <div class="d-flex justify-content-between align-items-center mb-4">\n'
content += '                        <h4 class="fw-bold mb-0"><i class="fas fa-user-circle me-2" style="color: var(--color-primary);"></i> My Profile</h4>\n'
content += '                        <button class="btn btn-primary-gradient" data-bs-toggle="modal" data-bs-target="#editProfileModal"><i class="fas fa-edit"></i> Edit Profile</button>\n'
content += '                    </div>\n'
content += '                    <div class="row g-4 mb-4">\n'
content += '                        <div class="col-md-4 text-center">\n'
content += '                            <div class="profile-avatar-large mx-auto mb-3"><i class="fas fa-user-circle" style="font-size: 8rem; color: var(--color-primary);"></i></div>\n'
content += '                            <h5 class="fw-bold mb-1" th:text="${studentProfile.fullName()}">Full Name</h5>\n'
content += '                            <span class="badge badge-primary">Student</span>\n'
content += '                        </div>\n'
content += '                        <div class="col-md-8">\n'
content += '                            <div class="row g-3">\n'
content += '                                <div class="col-sm-6">\n'
content += '                                    <label class="form-label text-muted small">Email</label>\n'
content += '                                    <p class="fw-semibold mb-0" style="word-break: break-all; overflow-wrap: break-word;" th:text="${studentProfile.email()}">email@example.com</p>\n'
content += '                                </div>\n'
content += '                                <div class="col-sm-6">\n'
content += '                                    <label class="form-label text-muted small">Phone</label>\n'
content += '                                    <p class="fw-semibold mb-0" style="word-break: break-all; overflow-wrap: break-word;" th:text="${studentProfile.phone()}">+1 234 567 890</p>\n'
content += '                                </div>\n'
content += '                                <div class="col-12">\n'
content += '                                    <label class="form-label text-muted small">Bio</label>\n'
content += '                                    <p class="mb-0" th:text="${studentProfile.bio()}">Bio description goes here...</p>\n'
content += '                                </div>\n'
content += '                                <div class="col-sm-6">\n'
content += '                                    <label class="form-label text-muted small">Skills</label>\n'
content += '                                    <p class="mb-0" th:text="${studentProfile.skills()}">Java, Spring Boot, SQL</p>\n'
content += '                                </div>\n'
content += '                                <div class="col-sm-6">\n'
content += '                                    <label class="form-label text-muted small">Experience Level</label>\n'
content += '                                    <p class="mb-0" th:text="${studentProfile.experienceLevel()}">Entry Level</p>\n'
content += '                                </div>\n'
content += '                                <div class="col-sm-6">\n'
content += '                                    <label class="form-label text-muted small">Education</label>\n'
content += '                                    <p class="mb-0" th:text="${studentProfile.education()}">Bachelor\'s Degree</p>\n'
content += '                                </div>\n'
content += '                                <div class="col-sm-6">\n'
content += '                                    <label class="form-label text-muted small">Location</label>\n'
content += '                                    <p class="mb-0" th:text="${studentProfile.location()}">New York, USA</p>\n'
content += '                                </div>\n'
content += '                            </div>\n'
content += '                        </div>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '            </div>\n'
content += '        </div>\n'
content += '    </div>\n'
content += '    <footer th:replace="~{fragments/footer::footer}"></footer>\n'
content += '    <div th:replace="~{fragments/header::scripts}"></div>\n'
content += '</body>\n'
content += '</html>\n'
write_file('src/main/resources/templates/student/profile.html', content)

# ===== FIX: employer/dashboard.html - properly closed =====
content = '<!DOCTYPE html>\n'
content += '<html xmlns:th="http://www.thymeleaf.org"\n      xmlns:sec="http://www.thymeleaf.org/extras/spring-security"\n      lang="en">\n'
content += '<head th:replace="~{fragments/header::head(\'Employer Dashboard - JobPortal\', \'Your recruitment dashboard\')}"></head>\n'
content += '<body>\n'
content += '    <div th:replace="~{fragments/employer-sidebar::sidebar(\'Dashboard\', \'dashboard\')}"></div>\n'
content += '    <div class="dashboard-main">\n'
content += '    <div class="container-fluid">\n'
content += '        <div class="glass-card-lg p-5 mb-5 fade-in">\n'
content += '            <div class="row align-items-center">\n'
content += '                <div class="col-lg-8">\n'
content += '                    <div class="d-flex align-items-center gap-4 mb-3">\n'
content += '                        <div class="profile-avatar" style="width: 72px; height: 72px; font-size: 2rem;">\n'
content += '                            <span th:text="${currentUser != null ? #strings.substring(currentUser.fullName, 0, 1) : \'E\'}">E</span>\n'
content += '                        </div>\n'
content += '                        <div>\n'
content += '                            <h2 class="fw-bold mb-1" style="font-size: 1.8rem;">Welcome back, <span th:text="${currentUser?.fullName ?: \'Employer\'}">Employer</span></h2>\n'
content += '                            <p style="color: var(--text-secondary);">Your recruitment hub. Manage jobs, review applicants, and find top talent.</p>\n'
content += '                        </div>\n'
content += '                    </div>\n'
content += '                    <div class="d-flex flex-wrap gap-3 mt-4">\n'
content += '                        <a th:href="@{/employer/jobs/post}" class="btn btn-primary-gradient"><i class="fas fa-plus"></i> Post New Job</a>\n'
content += '                        <a th:href="@{/employer/applicants}" class="btn btn-secondary-glass"><i class="fas fa-users"></i> View Applicants</a>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '                <div class="col-lg-4 d-none d-lg-block">\n'
content += '                    <div class="glass p-4 text-center">\n'
content += '                        <div style="font-size: 0.8rem; color: var(--text-muted); margin-bottom: 0.5rem;">Profile Completion</div>\n'
content += '                        <div style="font-size: 2.5rem; font-weight: var(--font-weight-extrabold); color: var(--color-primary);" th:text="${profileCompletion} ?: \'75%\'">75%</div>\n'
content += '                        <div class="progress mt-2" style="height: 6px;"><div class="progress-bar" style="width: 75%;"></div>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '            </div>\n'
content += '        </div>\n'
content += '        <div class="row g-4 mb-5">\n'
content += '            <div class="col-6 col-xl-2"><div class="stats-card card fade-in"><div class="stats-icon primary"><i class="fas fa-briefcase"></i></div><div class="stats-number count-up" th:attr="data-target=${stats != null ? stats.totalJobs : 0}" th:text="${stats?.totalJobs ?: 0}">0</div><div class="stats-label">Jobs Posted</div></div>\n'
content += '            <div class="col-6 col-xl-2"><div class="stats-card card fade-in"><div class="stats-icon success"><i class="fas fa-check-circle"></i></div><div class="stats-number count-up" th:attr="data-target=${stats != null ? stats.activeJobs : 0}" th:text="${stats?.activeJobs ?: 0}">0</div><div class="stats-label">Active Jobs</div></div>\n'
content += '            <div class="col-6 col-xl-2"><div class="stats-card card fade-in"><div class="stats-icon info"><i class="fas fa-users"></i></div><div class="stats-number count-up" th:attr="data-target=${stats != null ? stats.totalApplicants : 0}" th:text="${stats?.totalApplicants ?: 0}">0</div><div class="stats-label">Total Applicants</div></div>\n'
content += '            <div class="col-6 col-xl-2"><div class="stats-card card fade-in"><div class="stats-icon warning"><i class="fas fa-star"></i></div><div class="stats-number count-up" th:attr="data-target=${stats != null ? stats.shortlisted : 0}" th:text="${stats?.shortlisted ?: 0}">0</div><div class="stats-label">Shortlisted</div></div>\n'
content += '            <div class="col-6 col-xl-2"><div class="stats-card card fade-in"><div class="stats-icon pink"><i class="fas fa-calendar-check"></i></div><div class="stats-number count-up" th:attr="data-target=${stats != null ? stats.interviewsScheduled : 0}" th:text="${stats?.interviewsScheduled ?: 0}">0</div><div class="stats-label">Interviews</div></div>\n'
content += '            <div class="col-6 col-xl-2"><div class="stats-card card fade-in"><div class="stats-icon success"><i class="fas fa-handshake"></i></div><div class="stats-number count-up" th:attr="data-target=${stats != null ? stats.offersSent : 0}" th:text="${stats?.offersSent ?: 0}">0</div><div class="stats-label">Offers Sent</div></div>\n'
content += '        </div>\n'
content += '        <div class="row g-4">\n'
content += '            <div class="col-lg-8">\n'
content += '                <div class="card mb-4"><div class="card-header"><h5 class="fw-bold mb-0"><i class="fas fa-chart-line me-2" style="color: var(--color-primary);"></i> Applications Over Time</h5></div><div class="card-body"><canvas id="applicationsChart" height="220"></canvas></div>\n'
content += '                <div class="card mb-4"><div class="card-header d-flex justify-content-between"><h5 class="fw-bold mb-0"><i class="fas fa-user-plus me-2" style="color: var(--color-info);"></i> Recent Applicants</h5><a th:href="@{/employer/applicants}" class="btn btn-ghost btn-sm">View All <i class="fas fa-arrow-right ms-1"></i></a></div><div class="card-body p-0"><div th:if="${recentApplicants != null and !recentApplicants.isEmpty()}"><div th:each="app : ${recentApplicants}" class="activity-item px-4"><div class="activity-icon" style="background: var(--gradient-primary); color: #fff;"><span th:text="${#strings.substring(app.jobSeekerName ?: \'U\', 0, 1)}">U</span></div><div class="activity-content"><div class="activity-text"><strong th:text="${app.jobSeekerName()}">Name</strong> applied for <strong th:text="${app.jobTitle()}">Position</strong></div><div class="activity-time"><span th:text="${#temporals.format(app.appliedAt(), \'MMM dd, yyyy\')}">Date</span> <span class="status-badge" th:text="${app.status().name()}">Status</span></div></div><div th:if="${recentApplicants == null or recentApplicants.isEmpty()}" class="empty-state p-4"><div class="empty-icon" style="font-size: 2rem;"><i class="fas fa-user-plus"></i></div><h4>No applicants yet</h4><p>Post a job to start receiving applications.</p></div></div>\n'
content += '                <div class="card"><div class="card-header"><h5 class="fw-bold mb-0"><i class="fas fa-filter me-2" style="color: var(--color-primary);"></i> Hiring Pipeline</h5></div><div class="card-body"><div class="row g-3 text-center"><div class="col-3"><div class="glass p-3"><div class="fw-extrabold" style="font-size: 1.5rem; color: var(--color-warning);" th:text="${pipeline?.applied ?: 0}">0</div><div style="font-size: var(--font-size-xs); color: var(--text-muted);">Applied</div></div><div class="col-3"><div class="glass p-3"><div class="fw-extrabold" style="font-size: 1.5rem; color: var(--color-info);" th:text="${pipeline?.reviewing ?: 0}">0</div><div style="font-size: var(--font-size-xs); color: var(--text-muted);">Reviewing</div></div><div class="col-3"><div class="glass p-3"><div class="fw-extrabold" style="font-size: 1.5rem; color: var(--color-primary);" th:text="${pipeline?.shortlisted ?: 0}">0</div><div style="font-size: var(--font-size-xs); color: var(--text-muted);">Shortlisted</div></div><div class="col-3"><div class="glass p-3"><div class="fw-extrabold" style="font-size: 1.5rem; color: var(--color-success);" th:text="${pipeline?.hired ?: 0}">0</div><div style="font-size: var(--font-size-xs); color: var(--text-muted);">Hired</div></div></div>\n'
content += '            </div>\n'
content += '            <div class="col-lg-4">\n'
content += '                <div class="card mb-4"><div class="card-header"><h5 class="fw-bold mb-0"><i class="fas fa-trophy me-2" style="color: var(--color-warning);"></i> Top Jobs</h5></div><div class="card-body p-0"><div th:if="${topJobs != null and !topJobs.isEmpty()}"><div th:each="job : ${topJobs}" class="px-4 py-3" style="border-bottom: 1px solid var(--border-secondary);"><div class="fw-semibold" style="font-size: var(--font-size-sm);" th:text="${job.title()}">Job</div><div style="font-size: var(--font-size-xs); color: var(--text-muted);"><span th:text="${job.applicationCount()}">0</span> applicants</div></div><div th:if="${topJobs == null or topJobs.isEmpty()}" class="empty-state p-4"><p>Post your first job to see performance here.</p></div></div>\n'
content += '                <div class="card mb-4"><div class="card-header"><h5 class="fw-bold mb-0"><i class="fas fa-chart-pie me-2" style="color: var(--color-primary);"></i> Applications by Job</h5></div><div class="card-body"><canvas id="jobsPieChart" height="250"></canvas></div>\n'
content += '                <div class="card"><div class="card-header"><h5 class="fw-bold mb-0"><i class="fas fa-bolt me-2" style="color: var(--color-warning);"></i> Activity Feed</h5></div><div class="card-body p-0"><div th:if="${activities != null and !activities.isEmpty()}"><div th:each="act : ${activities}" class="activity-item px-4"><div class="activity-icon badge badge-info"><i class="fas fa-bell"></i></div><div class="activity-content"><div class="activity-text" th:text="${act.message}">Activity</div><div class="activity-time" th:text="${#temporals.format(act.createdAt(), \'MMM dd h:mm a\')}">Date</div></div><div th:if="${activities == null or activities.isEmpty()}" class="empty-state p-4"><p>No recent activity.</p></div></div>\n'
content += '            </div>\n'
content += '        </div>\n'
content += '    </div>\n'
content += '    </div>\n'
content += '    <div th:replace="~{fragments/header::scripts}"></div>\n'
content += '</body>\n'
content += '</html>\n'
write_file('src/main/resources/templates/employer/dashboard.html', content)

# ===== FIX: student/dashboard.html =====
content = '<!DOCTYPE html>\n'
content += '<html xmlns:th="http://www.thymeleaf.org"\n      xmlns:sec="http://www.thymeleaf.org/extras/spring-security"\n      lang="en">\n'
content += '<head th:replace="~{fragments/header::head(\'Student Dashboard - JobPortal\', \'Your personalized student dashboard\')}"></head>\n'
content += '<body>\n'
content += '    <div th:replace="~{fragments/student-sidebar::sidebar(\'Dashboard\', \'dashboard\')}"></div>\n'
content += '    <div class="dashboard-main">\n'
content += '    <div class="container-fluid">\n'
content += '        <div class="glass-card-lg p-5 mb-5 fade-in">\n'
content += '            <div class="row align-items-center">\n'
content += '                <div class="col-lg-8">\n'
content += '                    <div class="d-flex align-items-center gap-4 mb-3">\n'
content += '                        <div class="profile-avatar" style="width: 72px; height: 72px; font-size: 2rem;">\n'
content += '                            <span th:text="${currentUser != null ? #strings.substring(currentUser.fullName, 0, 1) : \'U\'}">U</span>\n'
content += '                        </div>\n'
content += '                        <div>\n'
content += '                            <h2 class="fw-bold mb-1" style="font-size: 1.8rem;">Welcome back, <span th:text="${currentUser?.fullName ?: \'User\'}">User</
