# Fix all remaining template files in one script

def write_file(path, content):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Written {len(content)} bytes to {path}')

# ===== FIX: student/profile.html =====
content = '<!DOCTYPE html>\n'
content += '<html xmlns:th="http://www.thymeleaf.org"\n      xmlns:sec="http://www.thymeleaf.org/extras/spring-security"\n      lang="en">\n'
content += '<head th:replace="~{fragments/header::head(\'My Profile - JobPortal\', \'Manage your profile\')}"></head>\n'
content += '<body>\n'
content += '    <div class="aurora-bg"></div>\n'
content += '    <div class="aurora-blob aurora-blob-1"></div>\n'
content += '    <div class="aurora-blob aurora-blob-2"></div>\n'
content += '    <div class="mouse-glow"></div>\n'
content += '    <nav th:replace="~{fragments/header::navbar}"></nav>\n'
content += '    <div class="container py-5" style="max-width: 1200px; margin-top: 76px;">\n'
content += '        <div class="row g-4">\n'
content += '            <div class="col-lg-3">\n'
content += '                <div th:replace="~{fragments/student-sidebar::sidebar(\'Profile\', \'profile\')}"></div>\n'
content += '            </div>\n'
content += '            <div class="col-lg-9">\n'
content += '                <div class="glass-card-lg p-4 fade-in">\n'
content += '                    <div class="d-flex justify-content-between align-items-center mb-4">\n'
content += '                        <h4 class="fw-bold mb-0"><i class="fas fa-user-circle me-2" style="color: var(--color-primary);"></i> My Profile</h4>\n'
content += '                        <button class="btn btn-primary-gradient" data-bs-toggle="modal" data-bs-target="#editProfileModal"><i class="fas fa-edit"></i> Edit Profile</button>\n'
content += '                    </div>\n'
content += '                    <div class="row g-4 mb-4">\n'
content += '                        <div class="col-md-4 text-center">\n'
content += '                            <div class="profile-avatar-large mx-auto mb-3"><i class="fas fa-user-circle" style="font-size: 8rem; color: var(--color-primary);"></i></div>\n'
content += '                            <h5 class="fw-bold mb-1" th:text="${studentProfile.fullName()}">Full Name</h5>\n'
content += '                            <span class="badge badge-primary">Student</span>\n'
content += '                        </div>\n'
content += '                        <div class="col-md-8">\n'
content += '                            <div class="row g-3">\n'
content += '                                <div class="col-sm-6">\n'
content += '                                    <label class="form-label text-muted small">Email</label>\n'
content += '                                    <p class="fw-semibold mb-0" style="word-break: break-all; overflow-wrap: break-word;" th:text="${studentProfile.email()}">email@example.com</p>\n'
content += '                                </div>\n'
content += '                                <div class="col-sm-6">\n'
content += '                                    <label class="form-label text-muted small">Phone</label>\n'
content += '                                    <p class="fw-semibold mb-0" style="word-break: break-all; overflow-wrap: break-word;" th:text="${studentProfile.phone()}">+1 234 567 890</p>\n'
content += '                                </div>\n'
content += '                                <div class="col-12">\n'
content += '                                    <label class="form-label text-muted small">Bio</label>\n'
content += '                                    <p class="mb-0" th:text="${studentProfile.bio()}">Bio description goes here...</p>\n'
content += '                                </div>\n'
content += '                                <div class="col-sm-6">\n'
content += '                                    <label class="form-label text-muted small">Skills</label>\n'
content += '                                    <p class="mb-0" th:text="${studentProfile.skills()}">Java, Spring Boot, SQL</p>\n'
content += '                                </div>\n'
content += '                                <div class="col-sm-6">\n'
content += '                                    <label class="form-label text-muted small">Experience Level</label>\n'
content += '                                    <p class="mb-0" th:text="${studentProfile.experienceLevel()}">Entry Level</p>\n'
content += '                                </div>\n'
content += '                                <div class="col-sm-6">\n'
content += '                                    <label class="form-label text-muted small">Education</label>\n'
content += '                                    <p class="mb-0" th:text="${studentProfile.education()}">Bachelor\'s Degree</p>\n'
content += '                                </div>\n'
content += '                                <div class="col-sm-6">\n'
content += '                                    <label class="form-label text-muted small">Location</label>\n'
content += '                                    <p class="mb-0" th:text="${studentProfile.location()}">New York, USA</p>\n'
content += '                                </div>\n'
content += '                            </div>\n'
content += '                        </div>\n'
content += '                    </div>\n'
content += '                </div>\n'
content += '            </div>\n'
content += '        </div>\n'
content += '    </div>\n'
content += '    <footer th:replace="~{fragments/footer::footer}"></footer>\n'
content += '    <div th:replace="~{fragments/header::scripts}"></div>\n'
content += '</body>\n'
content += '</html>\n'
write_file('src/main/resources/templates/student/profile.html', content)

# ===== FIX: student/dashboard.html =====
sd = '<!DOCTYPE html>\n'
sd += '<html xmlns:th="http://www.thymeleaf.org"\n      xmlns:sec="
